const state={data:null,year:null,query:'',selected:null};
const $=s=>document.querySelector(s);
const formatTime=s=>s==null?'—':`${Math.floor(s/3600)}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function edition(){return state.data.editions.find(e=>e.year===Number(state.year))}
function rows(){const id=edition()?.edition_id;return state.data.results.filter(r=>r.edition_id===id&&(!state.query||`${r.name} ${r.club||''}`.toLowerCase().includes(state.query.toLowerCase())))}
function renderFacts(){const all=state.data.results.filter(r=>r.edition_id===edition()?.edition_id), fin=all.filter(r=>r.status==='FINISHED'), dnf=all.filter(r=>r.status==='DNF');const med=a=>{const x=a.map(r=>r.finish_seconds).filter(Number.isFinite).sort((a,b)=>a-b);return x.length?formatTime(x[Math.floor((x.length-1)/2)]):'—'};const mean=a=>{const x=a.map(r=>r.finish_seconds).filter(Number.isFinite);return x.length?formatTime(Math.round(x.reduce((p,c)=>p+c,0)/x.length)):'—'};const f=fin.filter(r=>r.gender==='Kvinnor'||r.gender==='Damer'),m=fin.filter(r=>r.gender==='Män'||r.gender==='Herrar');const best=fin.filter(r=>Number.isFinite(r.finish_seconds)).sort((a,b)=>a.finish_seconds-b.finish_seconds)[0];$('#facts').innerHTML=`<div class="fact"><h3>STARTANDE</h3><strong>${all.length}</strong><small>importerade resultatposter</small></div><div class="fact"><h3>FULLFÖLJDE</h3><strong>${fin.length}</strong><small>${all.length?Math.round(fin.length/all.length*1000)/10:0}%</small></div><div class="fact"><h3>DNF</h3><strong>${dnf.length}</strong><small>explicit eller källstödd status</small></div><div class="fact gender"><h3>TIDER KVINNOR / MÄN</h3><strong><span class="f">Kvinnor median ${med(f)} · medel ${mean(f)}</span><span class="m">Män median ${med(m)} · medel ${mean(m)}</span></strong></div><div class="fact"><h3>SNABBASTE TID</h3><strong>${best?formatTime(best.finish_seconds):'—'}</strong><small>${best?best.name:'Ej fastställt'}</small></div>`}
function renderRows(){const rs=rows();$('#result-count').textContent=`${rs.length} träffar i vald upplaga`;$('#rows').innerHTML=rs.slice(0,300).map(r=>`<tr><td>${r.name||'—'}</td><td>${r.gender||'—'}</td><td>${r.club||'—'}</td><td class="status-${r.status.toLowerCase()}">${r.status}</td><td>${formatTime(r.finish_seconds)}</td><td><button data-id="${r.result_id}">Öppna</button></td></tr>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{state.selected=state.data.results.find(r=>r.result_id===b.dataset.id);renderRunner()})}
function renderRunner(){const r=state.selected;if(!r){$('#runner').className='runner empty';$('#runner').textContent='Välj en rad i resultatdatabasen för individuell visning.';return}$('#runner').className='runner';const obs=r.observations.length?r.observations.map(o=>`<li>${o.name} (${o.distance_km??'källavstånd saknas'} km): ${o.raw_time}</li>`).join(''):'<li>Inga importerade mellantidsobservationer för detta resultat.</li>';$('#runner').innerHTML=`<h3>${r.name}</h3><p>${r.status} · sluttid ${formatTime(r.finish_seconds)} · ${r.club||'klubb saknas'}</p><h4>Verkliga mellantider</h4><ul>${obs}</ul>`}
function render(){renderFacts();renderRows();renderRunner()}
fetch('data.json').then(r=>r.json()).then(data=>{state.data=data;const years=[...new Set(data.editions.map(e=>e.year))].sort((a,b)=>b-a);state.year=years[0];$('#year').innerHTML=years.map(y=>`<option>${y}</option>`).join('');$('#year').value=state.year;render()});$('#year').onchange=e=>{state.year=e.target.value;state.selected=null;render()};$('#search').oninput=e=>{state.query=e.target.value;renderRows()};
